### ISSUE TITLE
links and usage broken on website

### ISSUE THREAD

**Issue by DanielRuf** [airform/airform#1]
On airform.io the usage does not show the code but render the html form. Also contributing.md leads to a 404.

**Comment by mehmetkose** [comment]
Same here. Where is the source code bruh?

**Comment by cjpatoilo** [comment]
@DanielRuf @mehmetkose Is this problem still happening with you?

**Comment by DanielRuf** [comment]
This seems to be resolved now.

**Comment by cjpatoilo** [comment]
@DanielRuf thank you for reporting! 🙏
