### ISSUE TITLE
No confirmation mail

### ISSUE THREAD

**Issue by rradar** [airform/airform#19]
**Describe the bug**
I don't receive any confirmation mail from airform

**To Reproduce**
1. Go to `xyz.html`
2. Click on _edit_
3. Scroll down and add something like `<form method="post" action="https://airform.io/airform@domain.my">`
4. Upload to your webserver and fill out the form

**Screenshots**

![image](https://user-images.githubusercontent.com/34582688/77166332-f9231800-6aab-11ea-82a8-39392c7b3b9b.png)

**Expected behavior**
I should receive a verifiction mail from airform

**Additional context**
I tried various times on various days. Waited days to receive mail that might be stuck somewhere. Also checked the spam folder. I can send and receive mails without any problems on my domain.

**Comment by cjpatoilo** [comment]
@rradar Maybe has something wrong. Please, try again and let me know if you don't find the verification email.

ps: Sorry for the delay. Unfortunately, I've been sick some days ago.

**Comment by cjpatoilo** [comment]
@rradar Maybe has something wrong. 
Please, try again and let me know if you don't find the verification email.

**Comment by rradar** [comment]
hey @cjpatoilo thank's for your feedback! Hope you are healthy and feeling good again!

I tried again but still I don't receive any mail from airform. I checked again from other domains and my mail is perfectly reachable. No problems at all :thinking:

**Comment by cjpatoilo** [comment]
@rradar this case is strange to me. If don't have any problems, please, say me here what is your email? 

Otherwise, you send a private message on Twitter that I will analyze your case closely.

**Comment by rradar** [comment]
I just checked with a different email address on the same host and this time I received the confirmation mail.

In all it looks the problem lays with the mail host. Looks like they filter the mail before it arrives in my account.

I will close this one here and try to further investigate with my mail host.

Thank's for your help @cjpatoilo 

Stay save!

**Comment by BattleOfPlassey** [comment]
Yes it doesn't send confirmation request to me as well, In fact its not sending any emails now a days.
