### ISSUE TITLE
Captcha error

### ISSUE THREAD

**Issue by yanvancelis** [airform/airform#43]
Friends, I am getting this error when checking the google captcha when confirming the sending.

When I click submit, I click to confirm the captcha and, a little later, says that the "verification has expired".

Inspecting the page, in the network tab, I get a 404 error. Does anyone have a light?

**Comment by cjpatoilo** [comment]
@yanvancelis thank you for share this issue with us.
It was fixed. Now all works fine.

**Comment by cjpatoilo** [comment]
Now, I will close this issue. Please, feel free to open a new one if you find something wrong.
@yanvancelis thank you again.
